apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice-deployment
  labels:
    app: emailservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: emailservice
        image: docker.io/rusiruavb/email-service:latest
        ports:
        - containerPort: 9040
        env:
        - name: SENDER_EMAIL
          value: test@gmail.com
        - name: SENDER_PASSWORD
          value: testpassword
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
  - protocol: TCP
    port: 9040
    targetPort: 9040