apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice-deployement
  labels:
    app: orderservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - name: orderservice
        image: docker.io/rusiruavb/order-service:latest
        ports:
        - containerPort: 9090
        env:
        - name: MONGO_URL
          value: mongodb+srv://rusiru:RavB1998@linkup-cluster.a1bvi.mongodb.net/clicktocart?retryWrites=true&w=majority
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
  type: ClusterIP
  selector:
    app: orderservice
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090