name: ClickToCart CI/CD Pipeline

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  DOCKER_USER_RUSIRU: ${{secrets.DOCKER_USER_RUSIRU}}
  DOCKER_PASSWORD_RUSIRU: ${{secrets.DOCKER_PASSWORD_RUSIRU}}
  ORDER_REPO_NAME_RUSIRU: ${{secrets.ORDER_REPO_NAME_RUSIRU}}
  EMAIL_REPO_NAME_RUSIRU: ${{secrets.EMAIL_REPO_NAME_RUSIRU}}
  DOCKER_USER_SENURA: ${{secrets.DOCKER_USER_SENURA}}
  DOCKER_PASSWORD_SENURA: ${{secrets.DOCKER_PASSWORD_SENURA}}
  CART_REPO_NAME_SENURA: ${{secrets.CART_REPO_NAME_SENURA}}
  PRODUCT_REPO_NAME_SENURA: ${{secrets.PRODUCT_REPO_NAME_SENURA}}

jobs:
  order-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Work Dir
      run: echo $(pwd)
    - name: Docker login
      run: | # Login to Dockerhub - Rusriu
        docker login -u $DOCKER_USER_RUSIRU -p $DOCKER_PASSWORD_RUSIRU
    - name: Build order service docker image
      run: |
        cd src/order_service
        docker build . --file Dockerfile --tag $DOCKER_USER_RUSIRU/$ORDER_REPO_NAME_RUSIRU:v1.0.0
    - name: Push order service docker image
      run: docker push $DOCKER_USER_RUSIRU/$ORDER_REPO_NAME_RUSIRU:v1.0.0
  
  email-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: | # Login to Dockerhub - Rusriu
        docker login -u $DOCKER_USER_RUSIRU -p $DOCKER_PASSWORD_RUSIRU
    - name: Build email service docker image
      run: |
        cd src/email_service
        docker build . --file Dockerfile --tag $DOCKER_USER_RUSIRU/$EMAIL_REPO_NAME_RUSIRU:v1.0.0
    - name: Push email service docker image
      run: docker push $DOCKER_USER_RUSIRU/$EMAIL_REPO_NAME_RUSIRU:v1.0.0
  
  cart-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: Build with Maven
      run: |
        cd src/cart_service
        mvn clean package
    - name: Docker login
      run: | # Login to Dockerhub - Senura
        docker login -u $DOCKER_USER_SENURA -p $DOCKER_PASSWORD_SENURA
    - name: Build cart service docker image
      run: |
        cd src/cart_service
        docker build . --file Dockerfile --tag $DOCKER_USER_SENURA/$CART_REPO_NAME_SENURA:v1.0.1
    - name: Push cart service docker image
      run: docker push $DOCKER_USER_SENURA/$CART_REPO_NAME_SENURA:v1.0.1
  
  product-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: Build with Maven
      run: |
        cd src/product_service
        mvn clean package
    - name: Docker login
      run: | # Login to Dockerhub - Senura
        docker login -u $DOCKER_USER_SENURA -p $DOCKER_PASSWORD_SENURA
    - name: Build product service docker image
      run: |
        cd src/product_service
        docker build . --file Dockerfile --tag $DOCKER_USER_SENURA/$PRODUCT_REPO_NAME_SENURA:v1.0.1
    - name: Push cart service docker image
      run: docker push $DOCKER_USER_SENURA/$PRODUCT_REPO_NAME_SENURA:v1.0.1
  
  deploy:
    needs: [order-service, email-service, cart-service, product-service]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 🛠 Configure Kubernetes Credentials
      uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ctse
        resource-group: CTSE
    - name: ⬆️ Deploy to K8s
      run: kubectl apply -f release/